"""
SO WHATVER CODE I AM WRITTING HERE I AM FOLLOWING INDEXING SAME AS SAME AS "I HAVE SET IN PYTHON FILE IN C " 
JASAI WAHA PAI CODE LINE PAI TOPIC WISE SAME YAHA PAI BHI CODE LINE MAI TOPIC WISE SRIF YAHA PAI PYTHON MAI HAI 
"""

## 01 TO 07  ----> ARRAYS folder  in C 

### Names Are given 
### 08 to  ----> HASHING ...